import { Product } from "./inventory.types";

export const inventoryProducts: Product[] = [
  {
    id: '1',
    code: 'LAP-001',
    name: 'Laptop Pro 15"',
    category: 'Electrónicos',
    location: 'A1',
    description: 'Laptop empresarial con procesador i7 y 16GB RAM',
    tags: ['tecnología', 'oficina', 'portátil'],
    barcode: '7891234567890',
    brand: 'TechMaster',
    quantity: 25,
    status: 1, // 1 = En stock
    cost: 750.00,
    basePrice: 999.00,
    taxPercent: 10,
    price: 1098.90, // basePrice + (basePrice * taxPercent/100)
    thumbnail: 'watch-01-01.jpg',
    image: '',
    active: true
  },
  {
    id: '2',
    code: 'MOUSE-2023',
    name: 'Mouse Inalámbrico',
    category: 'Accesorios',
    location: 'A2',
    description: 'Mouse ergonómico con conexión Bluetooth',
    tags: ['accesorio', 'inalámbrico'],
    barcode: '7894561230123',
    brand: 'PeriTech',
    quantity: 0,
    status: 2, // 2 = Agotado
    cost: 12.50,
    basePrice: 29.99,
    taxPercent: 10,
    price: 32.99,
    thumbnail: 'watch-02-01.jpg',
    image: '',
    active: true
  },
  {
    id: '3',
    code: 'KB-ERGO',
    name: 'Teclado Ergonómico',
    category: 'Accesorios',
    location: 'A3',
    description: 'Teclado dividido para mayor comodidad',
    tags: ['ergonómico', 'oficina'],
    barcode: null, // No tiene código de barras asignado
    brand: 'PeriTech',
    quantity: 8,
    status: 3, // 3 = Bajo stock
    cost: 45.00,
    basePrice: 89.99,
    taxPercent: 10,
    price: 98.99,
    thumbnail: 'watch-03-01.jpg',
    image: '',
    active: true
  },
  {
    id: '4',
    code: 'MON-27G',
    name: 'Monitor 27" 4K',
    category: 'Electrónicos',
    location: 'A4',
    description: 'Monitor profesional para diseño gráfico',
    tags: ['monitor', 'alta resolución'],
    barcode: '7897894561230',
    brand: 'ViewPlus',
    quantity: 15,
    status: 1,
    cost: 300.00,
    basePrice: 499.00,
    taxPercent: 10,
    price: 548.90,
    thumbnail: 'watch-04-01.jpg',
    image: '',
    active: false // Producto descontinuado
  },
  {
    id: '5',
    code: 'HD-1TB',
    name: 'Disco Duro Externo 1TB',
    category: 'Almacenamiento',
    location: 'A5',
    description: 'Disco duro portátil USB 3.0',
    tags: ['almacenamiento', 'portátil'],
    barcode: '7890123456789',
    brand: 'DataSafe',
    quantity: 42,
    status: 1,
    cost: 35.00,
    basePrice: 59.99,
    taxPercent: 10,
    price: 65.99,
    thumbnail: 'watch-07-01.jpg',
    image: '',
    active: true
  },
  {
    id: '6',
    code: 'SSD-500',
    name: 'SSD 500GB',
    category: 'Almacenamiento',
    location: 'A6',
    description: 'Unidad de estado sólido de alta velocidad',
    tags: ['rápido', 'upgrade'],
    barcode: '7896543210987',
    brand: 'SpeedDisk',
    quantity: 3,
    status: 3,
    cost: 40.00,
    basePrice: 79.99,
    taxPercent: 10,
    price: 87.99,
    thumbnail: 'watch-06-01.jpg',
    image: '',
    active: true
  },
  {
    id: '7',
    code: 'DOCK-USB',
    name: 'Docking Station USB-C',
    category: 'Accesorios',
    location: 'B1',
    description: 'Convierte tu laptop en estación de trabajo',
    tags: ['accesorio', 'conectividad'],
    barcode: '7893216549870',
    brand: 'ConnectPro',
    quantity: 0,
    status: 2,
    cost: 65.00,
    basePrice: 129.99,
    taxPercent: 10,
    price: 142.99,
    thumbnail: 'watch-07-01.jpg',
    image: '',
    active: true
  },
  {
    id: '8',
    code: 'WEB-4K',
    name: 'Webcam 4K',
    category: 'Electrónicos',
    location: 'B2',
    description: 'Cámara web con micrófono integrado',
    tags: ['videoconferencia', 'streaming'],
    barcode: '7891472583690',
    brand: 'ViewPlus',
    quantity: 18,
    status: 1,
    cost: 85.00,
    basePrice: 149.99,
    taxPercent: 10,
    price: 164.99,
    thumbnail: 'watch-08-01.jpg',
    image: '',
    active: true
  },
  {
    id: '9',
    code: 'ROUT-AC',
    name: 'Router WiFi AC2100',
    category: 'Redes',
    location: 'B3',
    description: 'Router de doble banda para hogar',
    tags: ['wifi', 'conectividad'],
    barcode: '7893692581470',
    brand: 'NetLink',
    quantity: 5,
    status: 3,
    cost: 60.00,
    basePrice: 99.99,
    taxPercent: 10,
    price: 109.99,
    thumbnail: 'watch-09-01.jpg',
    image: '',
    active: true
  },
  {
    id: '10',
    code: 'PAD-COOL',
    name: 'Pad de Enfriamiento',
    category: 'Accesorios',
    location: 'C1',
    description: 'Base con ventiladores para laptop',
    tags: ['enfriamiento', 'accesorio'],
    barcode: '7892583691470',
    brand: 'CoolTech',
    quantity: 30,
    status: 1,
    cost: 15.00,
    basePrice: 29.99,
    taxPercent: 10,
    price: 32.99,
    thumbnail: 'watch-10-01.jpg',
    image: '',
    active: true
  }
];